# Generated by Django 6.0.5 on 2026-05-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='images/')),
                ('posisi', models.BooleanField(default=False)),
                ('jumlahKunjungan', models.IntegerField(default=0)),
                ('instansi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengunjungIstimewa',
            fields=[
                ('pengunjung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.pengunjung')),
                ('jabatan', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=100)),
            ],
            bases=('blog.pengunjung',),
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.DateTimeField(auto_now_add=True)),
                ('keluar', models.DateTimeField(null=True)),
                ('tujuan', models.TextField(blank=True, null=True)),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('jumlahHadir', models.IntegerField(default=0)),
                ('jumlahAlpa', models.IntegerField(default=0)),
                ('pengunjung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=20)),
                ('mulai', models.TimeField()),
                ('selesai', models.TimeField()),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.petugas')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.DateTimeField(auto_now_add=True)),
                ('keluar', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat'), ('IZIN', 'Izin'), ('ALPA', 'Alpa')], max_length=10)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.jadwal')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.petugas')),
            ],
        ),
    ]
