# Generated by Django 6.0.5 on 2026-05-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pengunjung_pengunjungistimewa_kunjungan_petugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_petugas', to='blog.petugas'),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='keluar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
