# Generated by Django 6.0.5 on 2026-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_absensi_petugas_alter_kunjungan_keluar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunjungan',
            name='keluar',
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='masuk',
        ),
        migrations.AddField(
            model_name='pengunjung',
            name='kode_qr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pengunjung',
            name='nik',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
