# Generated by Django 6.0.5 on 2026-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_kunjungan_keluar_remove_kunjungan_masuk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='nik',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
