# Generated by Django 6.0.5 on 2026-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_pengunjung_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='nik',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
