# Generated by Django 6.0.5 on 2026-05-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_pengunjung_nik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petugas',
            name='jumlahAlpa',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('Monday', 'Senin'), ('Tuesday', 'Selasa'), ('Wednesday', 'Rabu'), ('Thursday', 'Kamis'), ('Friday', 'Jumat'), ('Saturday', 'Sabtu'), ('Sunday', 'Minggu')], max_length=20),
        ),
    ]
