# Generated by Django 6.0.5 on 2026-05-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_petugas_jumlahalpa_alter_jadwal_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.jadwal'),
        ),
    ]
