# Generated by Django 6.0.5 on 2026-05-15 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_absensi_jadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjungan',
            name='keluar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='masuk',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
