# Generated by Django 6.0.5 on 2026-05-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_kunjungan_keluar_kunjungan_masuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_induk_buku', models.CharField(max_length=100, unique=True)),
                ('nomor_inventaris', models.CharField(max_length=100, unique=True)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('tanggal_inventaris', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIPINJAM', 'Dipinjam'), ('RUSAK', 'Rusak'), ('HILANG', 'Hilang')], default='TERSEDIA', max_length=20)),
                ('jenis_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.jenisbuku')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.DateTimeField(auto_now_add=True)),
                ('keluar', models.DateTimeField(blank=True, null=True)),
                ('batas_pengembalian', models.DateTimeField()),
                ('status', models.CharField(choices=[('DIPINJAM', 'Dipinjam'), ('SELESAI', 'Selesai')], default='DIPINJAM', max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pengunjung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengembalian', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TEPAT_WAKTU', 'Tepat Waktu'), ('TERLAMBAT', 'Terlambat')], max_length=20)),
                ('denda', models.IntegerField(default=0)),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.peminjaman')),
            ],
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.penulis'),
        ),
    ]
