# Generated by Django 6.0.5 on 2026-05-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_jenis_jenisbuku_penulis_buku_peminjaman_pengembalian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenisbuku',
            name='penulis',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='posisi',
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='bahasa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='edisi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='editor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='foto',
            field=models.ImageField(default='media/images/Cover/default.jpg', upload_to='images/Cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='harga',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='isbn_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.jenis'),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='nama_pertemuan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='negara',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='nomor_katalog',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='nomor_klasifikasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='nomor_panggil_setempat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='penerbit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='penerjemah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='pengarang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buku_pengarang', to='blog.penulis'),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='seri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='subjek',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='tanggal_pertemuan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenisbuku',
            name='tempat_pertemuan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='posisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jenisbuku',
            name='judul',
            field=models.TextField(),
        ),
    ]
