# Generated by Django 6.0.5 on 2026-05-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_jenisbuku_penulis_remove_pengunjung_posisi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengunjung',
            old_name='jumlahKunjungan',
            new_name='_jumlahKunjungan',
        ),
    ]
